# Pipeline variables
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dmaven.repo.local=.m2/repository --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  GIT_SUBMODULE_STRATEGY: recursive
  NODE_OPTIONS: "--max-old-space-size=8192"
  DOCKER_DISABLE: "true"  

# Cache policy - Share target folders between jobs - Note that key is related to a commit and is purged automatically after pipeline execution
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.m2/repository/**/*
    - $CI_PROJECT_DIR/**/target/**/*

include:
  - project: 'boost/template-ci/pipelines/common'
    file: 'docker/docker-template.yml'
  - project: 'bots/trivy-script'
    file: '/trivy-template-job.yml'   

default:
  image: maven:3.6.0-jdk-11
  before_script:
    - apt update && apt install -y gettext-base build-essential
    - envsubst '${MVN_GROUP} ${MVN_RELEASE} ${MVN_SNAPSHOTS}' < pom.xml > pom.subst && mv -f pom.subst pom.xml

# Stages definition
stages:
  - build
  - test
  - pre_docker
  - docker  
  - deploy

# Build job with maven plugin execution policies define in parent pom
.signalementapi:build:
  script:
    - mvn $MAVEN_CLI_OPTS -U clean package ${OPTS} -Pprod,mapfishapp-signalement
  stage: build
  tags: 
    - iaas
  artifacts:
    paths:
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip
      - $CI_PROJECT_DIR/georchestra-signalement-mapstore-addon/dist/SignalementExtension.zip
      - $CI_PROJECT_DIR/georchestra-signalement-mapstore-management-addon/dist/SignalementManagementExtension.zip
      - $CI_PROJECT_DIR/georchestra-signalement-front-management/target/georchestra-signalement-front-management-angular-dist.zip
  interruptible: true

signalementapi:build:
  extends: .signalementapi:build
  except:
    refs:
      - master
      - open/master  

      
signalementapi:build:master:
  extends: .signalementapi:build
  only:
    refs:
      - master
      - open/master   
  variables:
    OPTS: "-DskipTests"  

# Sonar code quality analysis - note a full test coverage report through a jacoco.exec merged file in base project folder
.signalementapi:sonar:
  stage: test
  tags: 
    - iaas  
  allow_failure: true
  script:
    - >
      mvn $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      ${BRANCH}
  interruptible: true
  
signalementapi:sonar:
  extends: .signalementapi:sonar
  dependencies:
    - signalementapi:build
  except:
    refs:
      - master
      - open/master
  variables:
    BRANCH: -Dsonar.branch.name=$CI_COMMIT_REF_NAME
            

# On master, do not use branch parameter
signalementapi:sonar:master:
  extends: .signalementapi:sonar
  dependencies:
    - signalementapi:build:master
  only:
    refs:
      - open/master
      
# Copie des artifacts dans les répertoires des images dockers
signalementapi:pre_docker:
  stage: pre_docker
  only:
    refs:
      - master
      - open/master
      - open/develop
      - /^release.*/
  script:
    - ls -l $CI_PROJECT_DIR/georchestra-signalement-api/target/
    - cp $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar $CI_PROJECT_DIR/docker/rennes-metropole/signalement-backend/signalement.jar
    - cp $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar $CI_PROJECT_DIR/docker/template/signalement-backend/signalement.jar
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-front-management/target/georchestra-signalement-front-management-angular-dist.zip $CI_PROJECT_DIR/docker/rennes-metropole/signalement-front-management/georchestra-signalement-front-management-angular-dist.zip
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-front-management/target/georchestra-signalement-front-management-angular-dist.zip $CI_PROJECT_DIR/docker/template/signalement-front-management/georchestra-signalement-front-management-angular-dist.zip
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/**.war'
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/**.jar'
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/*.zip'
      - '$CI_PROJECT_DIR/docker/**/**.war'
      - '$CI_PROJECT_DIR/docker/**/**.zip'
      - '$CI_PROJECT_DIR/docker/**/**.jar'

signalementapi:docker2:build:
  extends: ['.docker:build']
  needs:
    - signalementapi:pre_docker
  dependencies:
    - signalementapi:pre_docker
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /.*develop/ || $CI_COMMIT_BRANCH =~ /.*master/ || $CI_COMMIT_BRANCH =~ /^release.*/'
  timeout: 1h
  artifacts:
    paths:
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/**.war'
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/**.jar'
      - '$CI_PROJECT_DIR/georchestra-signalement-api/target/*.zip'   
      - '$CI_PROJECT_DIR/docker/**/**.war'
      - '$CI_PROJECT_DIR/docker/**/**.zip'
      - '$CI_PROJECT_DIR/docker/**/**.jar'       

trivyscan:back: 
  extends: 
    - .trivy-scan
  stage: docker
  needs:
    - signalementapi:docker2:build
  dependencies:
    - signalementapi:docker2:build
  variables:
    TRIVY_DOCKER_SCAN: glregistry.boost.open.global/rennes-metropole/signalement/signalement-backend/rennes-metropole/signalement-backend:open-develop
  only:
    refs:
      - open/develop

trivyscan:front: 
  extends: 
    - .trivy-scan
  stage: docker
  needs:
    - signalementapi:docker2:build
  dependencies:
    - signalementapi:docker2:build
  variables:
    TRIVY_DOCKER_SCAN: glregistry.boost.open.global/rennes-metropole/signalement/signalement-backend/rennes-metropole/signalement-front-management:open-develop
  only:
    refs:
      - open/develop

.signalementapi:deploy:
  stage: deploy
  image: glregistry.boost.open.global/boost/docker/mvn-node-jdk11-ansible:latest
  tags: 
    - iaas
  cache: {}
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$ansible_private_key" | base64 -d)
  script:
    - ls $CI_PROJECT_DIR/georchestra-signalement-api/target/
    - ls $CI_PROJECT_DIR/georchestra-signalement-mapstore*
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api.war
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api.jar 
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api-addon.zip
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-mapstore-addon/dist/SignalementExtension.zip $CI_PROJECT_DIR/ansible/dockerize/files/SignalementExtension.zip
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-mapstore-management-addon/dist/SignalementManagementExtension.zip $CI_PROJECT_DIR/ansible/dockerize/files/SignalementManagementExtension.zip
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-front-management/target/georchestra-signalement-front-management-angular-dist.zip $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-front-management.zip
    - cd $CI_PROJECT_DIR/ansible  
    #- chmod og-rw key/id_rsa
    - cp ${ANSIBLE_VAR_FILE} $HOME/signalement_var.yml
    - ansible-playbook signalement-docker.yml -v -i "${SERVER}," -u root --ssh-common-args=-oStrictHostKeyChecking=no
  interruptible: true
 
signalementapi:deploy:
  extends: .signalementapi:deploy
  dependencies:
    - signalementapi:build
  only:
    refs:
      - open/develop
  variables:
    SERVER: "ren1vml0096"
    ANSIBLE_VAR_FILE: signalement_dev_var.yml

signalementapi:deploy:master:
  extends: .signalementapi:deploy
  dependencies:
    - signalementapi:build:master
  only:
    refs:
      - open/master
  variables:
    SERVER: "ren1vml0095"
    ANSIBLE_VAR_FILE: signalement_rct_var.yml
