# Pipeline variables
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Dmaven.repo.local=.m2/repository --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache policy - Share target folders between jobs - Note that key is related to a commit and is purged automatically after pipeline execution
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/.m2/repository/**/*
    - $CI_PROJECT_DIR/**/target/**/*

default:
  image: maven:3.6.0-jdk-11
  before_script:
    - apt update && apt install -y gettext-base
    - envsubst '${MVN_GROUP} ${MVN_RELEASE} ${MVN_SNAPSHOTS}' < pom.xml > pom.subst && mv -f pom.subst pom.xml

# Stages definition
stages:
  - build
  - test
  - deploy

# Build job with maven plugin execution policies define in parent pom
signalementapi:build:
  script:
    - sh ./mvnw $MAVEN_CLI_OPTS -U package
  stage: build
  except:
    refs:
      - master
      - open/master  
  tags: 
   - cdp-rennes  
  artifacts:
    paths:
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip
      
signalementapi:build:master
  script:
    - sh ./mvnw $MAVEN_CLI_OPTS -U package -DskipTests
  stage: build
  tags: 
   - cdp-rennes
  only:
    refs:
      - master
      - open/master   
  artifacts:
    paths:
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.jar
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war
      - $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip      

# Sonar code quality analysis - note a full test coverage report through a jacoco.exec merged file in base project folder
signalementapi:sonar:
  stage: test
  dependencies:
    - signalementapi:build
  except:
    refs:
      - master
      - open/master
  allow_failure: true
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
            

# On master, do not use branch parameter
signalementapi:sonar:master:
  stage: test
  dependencies:
    - signalementapi:build
  only:
    refs:
      - open/master
  script:
    - >
      sh ./mvnw $MAVEN_CLI_OPTS -U compile sonar:sonar
      -Dsonar.host.url=$SONAR_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

signalementapi:deploy:
  stage: deploy
  tags: 
   - cdp-rennes
  image: ansible/ansible-runner
  dependencies:
    - signalementapi:build
  only:
    refs:
      - open/develop
  script:
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api.war 
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api-addon.zip
    - cd $CI_PROJECT_DIR/ansible  
    - chmod og-rw key/id_rsa
    - cp signalement_dev_var.yml $HOME/signalement_var.yml
    - ansible-playbook signalement-docker.yml -v -i "10.50.1.21," -u root --private-key=key/id_rsa --ssh-common-args=-oStrictHostKeyChecking=no

signalementapi:deploy:master:
  stage: deploy
  tags: 
   - cdp-rennes  
  image: ansible/ansible-runner
  dependencies:
    - signalementapi:build
  only:
    refs:
      - open/master
  script:
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*.war $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api.war 
    - cp -f $CI_PROJECT_DIR/georchestra-signalement-api/target/georchestra-signalement-api-*-addon.zip $CI_PROJECT_DIR/ansible/dockerize/files/georchestra-signalement-api-addon.zip
    - cd $CI_PROJECT_DIR/ansible  
    - chmod og-rw key/id_rsa
    - cp signalement_dev_var.yml $HOME/signalement_var.yml
    - ansible-playbook signalement-docker.yml -v -i "194.2.68.134," -u root --private-key=key/id_rsa --ssh-common-args=-oStrictHostKeyChecking=no
    