image:
  tag: open-develop
  env:
    - name: SIGNALEMENT_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: signalement-secret-qua
          key: database.signalement.password
    - name: SIGNALEMENT_LDAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: signalement-secret-qua
          key: ldap.signalement.password
    - name: SIGNALEMENT_BDD_HOST
      value: georchestra-bdd-qua-georchestra-service-bdd
      
    - name: SWAGGER_SERVER
      value: https://search-application-qua.shom-search.karbon.open.global/