---
# create root directory
- name: Creates directory application
  file:
    state: directory
    mode: 0775
    path: "{{ item }}"
  with_items:
    - "{{signalement_image_directory}}/"
    - "{{signalement_image_directory}}/signalement"
    - "{{signalement_config_directory}}/signalement"
        
# copy addon
- name: Copy addon to mapfishapp
  unarchive:
    src: "{{ signalement_addon_name }}"
    dest: "{{signalement_addon_directory}}"
    remote_src: no
    mode: 0775
   
- name: Set backend url
  replace:
    destfile: "{{signalement_addon_directory}}/signalement/manifest.json"
    regexp: '\"http://.*\"'
    replace: '"{{signalement_backend_url}}"'
    backup: yes  

# update security proxy
- name: Check whether targets-mapping.properties contains signalement
  command: grep -Fcq "signalement" "{{ signalement_config_directory }}/security-proxy/targets-mapping.properties"
  register: checksecuritysignalement
  check_mode: no
  ignore_errors: yes
  changed_when: no

- name: Update targets-mapping.properties if needed
  when: checksecuritysignalement.rc == 1
  shell:
    cmd: echo "signalement=http://signalement:{{signalement_server_port}}/signalement" >> "{{ signalement_config_directory }}/security-proxy/targets-mapping.properties"    

# copy images 
- name: Copy signalement api Dockerfile
  template:
    src: Dockerfile.api
    dest: "{{ signalement_image_directory }}/Dockerfile"
    mode: 0770
    
- name: Copy signalement war
  copy:
    src: "{{ signalement_war_name }}"
    dest: "{{ signalement_image_directory }}/signalement.war"
    mode: 0770 
   
- name: Copy signalement api properties file
  template:
    src: signalement.properties.j2
    dest: "{{ signalement_config_directory }}/signalement/signalement.properties"
    mode: 0770

- name: Copy default api properties file
  template:
    src: default.properties.j2
    dest: "{{ signalement_config_directory }}/default.properties"
    mode: 0777
        
#- name: Copy tomcat lib jar
#  copy:
#    src: "tomcat-juli.jar"
#    dest: "{{ signalement_image_directory }}/signalement/WEB-INF/lib/tomcat-juli.jar"
#    mode: 0770
  
- name: Build signalement api image
  shell: 
    cmd: docker build -t signalement-image {{signalement_image_directory}}
    chdir: "{{signalement_image_directory}}"  
    
# install yaml-merge
- name: Clone yaml-merge
  shell: 
    chdir: /tmp
    cmd: rm -rf /tmp/yaml-merge; git clone https://github.com/OndraZizka/yaml-merge.git 
    
- name: Override yaml-merge
  copy: 
    src: "YmlMerger.java"
    dest: "/tmp/yaml-merge/src/main/java/org/cobbzilla/util/yml"
    mode: 0664    
    
- name: Build yaml-merge
  shell:
    chdir: /tmp
    cmd: cd yaml-merge ;  mvn -Drelease package

# update docker compose file
- name: Copy signalement docker compose file
  template:
    src: docker-compose.yml.j2
    dest: "/tmp/yaml-merge/docker-signalement.yml"
    mode: 0664
    
- name: Copy original docker compose file
  copy:
    src: "{{signalement_docker_directory}}/docker-compose.yml"
    dest: "/tmp/yaml-merge/docker-compose.yml"
    remote_src: true
    mode: 0664    
    
- name: Merge docker compose file
  shell:
    chdir: "/tmp/yaml-merge"
    cmd: bin/yaml-merge.sh "docker-compose.yml" "docker-signalement.yml" > "{{signalement_docker_directory}}/docker-compose.yml"
    
#- name: Stop docker compose
#  shell:
#    cmd: docker-compose down
#    chdir: "{{signalement_docker_directory}}"
    
- name: Restart docker compose
  shell:
    cmd: docker-compose up -d --build
    chdir: "{{signalement_docker_directory}}"    