image:
  tag: open-develop
  env:
    - name: SIGNALEMENT_DATASOURCE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: signalement-secret-dev
          key: database.signalement.password
    - name: SIGNALEMENT_LDAP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: signalement-secret-dev
          key: ldap.signalement.password
    - name: SIGNALEMENT_BDD_HOST
      value: georchestra-bdd-dev-georchestra-service-bdd
      
    - name: SWAGGER_SERVER
      value: https://signalement-back-dev.rennes-metropole-georchestra.karbon.open.global