FROM httpd:2.4.48-alpine
USER root
ENV TZ=Europe/Paris

ADD georchestra-signalement-front-management.zip /usr/local/apache2/htdocs/front.zip
ADD httpd.conf /usr/local/apache2/conf

RUN cd /usr/local/apache2/htdocs &&\
    unzip front.zip &&\
    rm front.zip &&\
    mv front-management/* . &&\
    rm -rf front-management
