name: "signalement"

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking out"
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'      

    - name: "Setting up Java"
      uses: actions/setup-java@v1
      with:
        java-version: '17.x'

    - name: "Maven repository caching"
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: signalement-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: "Calculating docker image tag"
      id: version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: "Build a docker image for back-office"
      run: mvn -B clean package -Pdocker,prod -DskipTests -DskipDockerPush -DdockerImageName=sigrennesmetropole/geor_signalement:${{ steps.version.outputs.VERSION }}

    - name: "Build a docker image for front-office"
      run: mvn -B clean package -Pdocker-front-management,prod -DskipTests -DskipDockerPush -DdockerImageName=sigrennesmetropole/geor_signalement_admin:${{ steps.version.outputs.VERSION }}

    - name: "Logging in docker.io"
      uses: azure/docker-login@v1
      with:
        username: '${{ secrets.DOCKER_HUB_USERNAME }}'
        password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

    - name: "Pushing latest to docker.io"
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag sigrennesmetropole/geor_signalement:${{ steps.version.outputs.VERSION }} sigrennesmetropole/geor_signalement:latest
        docker push sigrennesmetropole/geor_signalement:latest
        docker tag sigrennesmetropole/geor_signalement_admin:${{ steps.version.outputs.VERSION }} sigrennesmetropole/geor_signalement_admin:latest
        docker push sigrennesmetropole/geor_signalement_admin:latest

    - name: "Pushing release tag to docker.io"
      if: contains(github.ref, 'refs/tags/')
      run: |
        docker push sigrennesmetropole/geor_signalement:${{ steps.version.outputs.VERSION }}
        docker push sigrennesmetropole/geor_signalement_admin:${{ steps.version.outputs.VERSION }}

    - name: "Remove SNAPSHOT jars from repository"
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
 

